name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirements.txt
          python main.py  # create score.json
 
          # Create CML report
          cat score.json >> report.md
          # echo '![](./plot.png "Confusion Matrix")' >> report.md
         
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
